# -*- coding: utf-8 -*-
"""blackBoxRipper-2025-03-18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dG3gyWmY8212rkl1VonE8I_YiQWkRnIC
"""

!git clone https://github.com/antoniobarbalau/black-box-ripper.git

# Commented out IPython magic to ensure Python compatibility.
# %cd black-box-ripper
!pip install -r requirements.txt
!mkdir -p checkpoints
!pip install numpy==1.26.4
!python base_experiment.py --true_dataset cifar10 --teacher alexnet --student half_alexnet --generator cifar_100_6_classes_gan

predictor_dict = {
    'half_lenet': predictors.HalfLeNet,
    'inceptionv3': predictors.InceptionV3,
    'lenet': predictors.LeNet,
    'resnet18': predictors.ResNet18,
    'vgg': predictors.VGG,
    'alexnet': predictors.Alexnet,
    'half_alexnet': predictors.HalfAlexnet
}
dataset_dict = {
    'cifar10': datasets.CIFAR10,
    # 'discrepancy': datasets.Discrepancy,
    # 'discrepancy_kl': datasets.Discrepancy_KL,
    # 'curriculum': datasets.Curriculum,
    'fmnist': datasets.FMNIST,
    'optimized': datasets.OptimizedFromGenerator,
    'random': datasets.RandomFromGenerator,
    'split_fmnist': datasets.SplitFMNIST,
    # 'two_gans': datasets.TwoGANs,
}
generator_dict = {
    'cifar_10_gan': generators.SNGAN,
    'cifar_100_90_classes_gan': generators.SNGAN,
    'cifar_100_40_classes_gan': generators.SNGAN,
    'cifar_10_vae': generators.VAE,
    'cifar_100_6_classes_gan': generators.Progan,
    'cifar_100_10_classes_gan': generators.Progan,
}
generator_prepare_dict = {
    'cifar_10_gan': trainer.train_or_restore_cifar_10_gan,
    'cifar_100_90_classes_gan': trainer.train_or_restore_cifar_100_90_classes_gan,
    'cifar_100_40_classes_gan': trainer.train_or_restore_cifar_100_40_classes_gan,
    'cifar_10_vae': trainer.train_or_restore_cifar_10_vae,
    'cifar_100_6_classes_gan': trainer.train_or_restore_cifar_100_6_classes_gan,
    'cifar_100_10_classes_gan': trainer.train_or_restore_cifar_100_10_classes_gan,
}



!python base_experiment.py --true_dataset cifar10 --teacher alexnet --student half_alexnet --generator cifar_100_6_classes_gan



"""conda create --name Python3.9-BlackBoxRipper python=3.9

conda activate Python3.9-BlackBoxRipper

pip install -r requirements.txt

mkdir -p checkpoints

pip install numpy==1.26.4

python base_experiment.py --true_dataset cifar10 --teacher alexnet --student half_alexnet --generator cifar_100_6_classes_gan

"""

#!python /content/black-box-ripper/generators/cifar_vae/train_vae.py