# -*- coding: utf-8 -*-
"""reproduce_black_box_ripper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X9OAyKnr1f_JE8zUfBzTQGilSqVG261l
"""

!pip install torch-optimizer

import torch
import torch.nn as nn
import torchvision
from torchvision import transforms

import sys
sys.path.append('..')
import torch_optimizer as optim
#from torch_optimizer import optimize, optimize_to_grayscale

import numpy as np
from numpy import sqrt
import os
import time

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

generator= 'cifar_100_6_classes_gan'
model_class = 'HalfAlexnet'



epochs = 200
size = 32


optim = 'adam' # type = str
#proxy_dataset', type = str, default = 'cifar10')
#sample_optimization', type = str, default = 'class')
samples = 'optimized'



#true_dataset = 'cifar10'
true_dataset_n_classes = 10

"""# models"""

class Alexnet(nn.Module):
    def __init__(self, name, n_outputs=10):
        super(Alexnet, self).__init__()

        self.name = name
        self.num_classes = n_outputs

        self.conv1 = nn.Conv2d(3, 48, 5, stride=1, padding=2)
        self.conv1.bias.data.normal_(0, 0.01)
        self.conv1.bias.data.fill_(0)

        self.relu = nn.ReLU()
        self.lrn = nn.LocalResponseNorm(2)
        self.pad = nn.MaxPool2d(3, stride=2)

        self.batch_norm1 = nn.BatchNorm2d(48, eps=0.001)

        self.conv2 = nn.Conv2d(48, 128, 5, stride=1, padding=2)
        self.conv2.bias.data.normal_(0, 0.01)
        self.conv2.bias.data.fill_(1.0)

        self.batch_norm2 = nn.BatchNorm2d(128, eps=0.001)

        self.conv3 = nn.Conv2d(128, 192, 3, stride=1, padding=1)
        self.conv3.bias.data.normal_(0, 0.01)
        self.conv3.bias.data.fill_(0)

        self.batch_norm3 = nn.BatchNorm2d(192, eps=0.001)

        self.conv4 = nn.Conv2d(192, 192, 3, stride=1, padding=1)
        self.conv4.bias.data.normal_(0, 0.01)
        self.conv4.bias.data.fill_(1.0)

        self.batch_norm4 = nn.BatchNorm2d(192, eps=0.001)

        self.conv5 = nn.Conv2d(192, 128, 3, stride=1, padding=1)
        self.conv5.bias.data.normal_(0, 0.01)
        self.conv5.bias.data.fill_(1.0)

        self.batch_norm5 = nn.BatchNorm2d(128, eps=0.001)

        self.fc1 = nn.Linear(1152,512)
        self.fc1.bias.data.normal_(0, 0.01)
        self.fc1.bias.data.fill_(0)

        self.drop = nn.Dropout(p=0.5)

        self.batch_norm6 = nn.BatchNorm1d(512, eps=0.001)

        self.fc2 = nn.Linear(512,256)
        self.fc2.bias.data.normal_(0, 0.01)
        self.fc2.bias.data.fill_(0)

        self.batch_norm7 = nn.BatchNorm1d(256, eps=0.001)

        self.fc3 = nn.Linear(256,10)
        self.fc3.bias.data.normal_(0, 0.01)
        self.fc3.bias.data.fill_(0)

        self.soft = nn.Softmax()

    def forward(self, x):
        layer1 = self.batch_norm1(self.pad(self.lrn(self.relu(self.conv1(x)))))
        layer2 = self.batch_norm2(self.pad(self.lrn(self.relu(self.conv2(layer1)))))
        layer3 = self.batch_norm3(self.relu(self.conv3(layer2)))
        layer4 = self.batch_norm4(self.relu(self.conv4(layer3)))
        layer5 = self.batch_norm5(self.pad(self.relu(self.conv5(layer4))))
        flatten = layer5.view(-1, 128*3*3)
        fully1 = self.relu(self.fc1(flatten))
        fully1 = self.batch_norm6(self.drop(fully1))
        fully2 = self.relu(self.fc2(fully1))
        fully2 = self.batch_norm7(self.drop(fully2))
        logits = self.fc3(fully2)
        #softmax_val = self.soft(logits)

        return logits

class HalfAlexnet(nn.Module):
    def __init__(self, name, n_outputs=10):
        super(HalfAlexnet, self).__init__()

        self.name = name
        self.num_classes = n_outputs

        self.conv1 = nn.Conv2d(3, 24, 5, stride=1, padding=2)
        self.conv1.bias.data.normal_(0, 0.01)
        self.conv1.bias.data.fill_(0)

        self.relu = nn.ReLU()
        self.lrn = nn.LocalResponseNorm(2)
        self.pad = nn.MaxPool2d(3, stride=2)

        self.batch_norm1 = nn.BatchNorm2d(24, eps=0.001)

        self.conv2 = nn.Conv2d(24, 64, 5, stride=1, padding=2)
        self.conv2.bias.data.normal_(0, 0.01)
        self.conv2.bias.data.fill_(1.0)

        self.batch_norm2 = nn.BatchNorm2d(64, eps=0.001)

        self.conv3 = nn.Conv2d(64, 96, 3, stride=1, padding=1)
        self.conv3.bias.data.normal_(0, 0.01)
        self.conv3.bias.data.fill_(0)

        self.batch_norm3 = nn.BatchNorm2d(96, eps=0.001)

        self.conv4 = nn.Conv2d(96, 96, 3, stride=1, padding=1)
        self.conv4.bias.data.normal_(0, 0.01)
        self.conv4.bias.data.fill_(1.0)

        self.batch_norm4 = nn.BatchNorm2d(96, eps=0.001)

        self.conv5 = nn.Conv2d(96, 64, 3, stride=1, padding=1)
        self.conv5.bias.data.normal_(0, 0.01)
        self.conv5.bias.data.fill_(1.0)

        self.batch_norm5 = nn.BatchNorm2d(64, eps=0.001)

        self.fc1 = nn.Linear(576,256)
        self.fc1.bias.data.normal_(0, 0.01)
        self.fc1.bias.data.fill_(0)

        self.drop = nn.Dropout(p=0.5)

        self.batch_norm6 = nn.BatchNorm1d(256, eps=0.001)

        self.fc2 = nn.Linear(256,128)
        self.fc2.bias.data.normal_(0, 0.01)
        self.fc2.bias.data.fill_(0)

        self.batch_norm7 = nn.BatchNorm1d(128, eps=0.001)

        self.fc3 = nn.Linear(128,10)
        self.fc3.bias.data.normal_(0, 0.01)
        self.fc3.bias.data.fill_(0)

        self.soft = nn.Softmax()

    def forward(self, x):
        layer1 = self.batch_norm1(self.pad(self.lrn(self.relu(self.conv1(x)))))
        layer2 = self.batch_norm2(self.pad(self.lrn(self.relu(self.conv2(layer1)))))
        layer3 = self.batch_norm3(self.relu(self.conv3(layer2)))
        layer4 = self.batch_norm4(self.relu(self.conv4(layer3)))
        layer5 = self.batch_norm5(self.pad(self.relu(self.conv5(layer4))))
        flatten = layer5.view(-1, 64*3*3)
        fully1 = self.relu(self.fc1(flatten))
        fully1 = self.batch_norm6(self.drop(fully1))
        fully2 = self.relu(self.fc2(fully1))
        fully2 = self.batch_norm7(self.drop(fully2))
        logits = self.fc3(fully2)
        #softmax_val = self.soft(logits)

        return logits

"""# Initialize"""

def initialize_model(name, n_outputs):

    model = model_class(name, n_outputs).to(device)

    return model

"""# datasets"""

class CIFAR10(object):
    def __init__(self, input_size = 32):
        self.n_classes = 10
        transform = transforms.Compose([
            transforms.Resize(input_size),
            transforms.ToTensor(),
            transforms.Normalize(
                (.5,), (.5,)
            ),
        ])
        self.train_dataset = torchvision.datasets.CIFAR10(
            root = '../data',
            train = True,
            download = True,
            transform = transform
        )
        self.test_dataset = torchvision.datasets.CIFAR10(
            root = '../data',
            train = False,
            download = True,
            transform = transform
        )

    def train_dataloader(self, *args, **kwargs):
        return torch.utils.data.DataLoader(
            self.train_dataset,
            batch_size = 64,
            shuffle = True,
            num_workers = 2,
            drop_last = True
        )

    def test_dataloader(self, *args, **kwrk):
        return torch.utils.data.DataLoader(
            self.test_dataset,
            batch_size = 16,
            num_workers = 2,
            drop_last = False
        )

"""# functions"""

def train_or_restore_predictor_adam(model, dataset, loss_type = 'categorical', n_epochs = 50,):

    model_exists = False
    ckpt_path = f'./checkpoints/{model.name}_state_dict'
    if os.path.exists(ckpt_path):
        model.load_state_dict(torch.load(ckpt_path, map_location = device))
        model.to(device)
        model_exists = True

    training_was_in_progress = False
    root_optimizer_ckpt_path = f'optimizer_for_{model.name}_state_dict'
    optimizer_ckpt_path = root_optimizer_ckpt_path
    for filename in os.listdir('./checkpoints'):
        if optimizer_ckpt_path in filename:
            training_was_in_progress = True
            optimizer_ckpt_path = filename

    if model_exists and not training_was_in_progress:
        model.eval()
        return

    lr = 0.001
    optimizer = torch.optim.Adam( model.parameters(), lr = lr,)
    if training_was_in_progress:
        optimizer.load_state_dict(torch.load(f'./checkpoints/{optimizer_ckpt_path}'))
    loss_function = torch.nn.CrossEntropyLoss()
    if loss_type == 'binary':
        loss_function = torch.nn.BCELoss()

    has_val = 'val_dataset' in dataset.__dict__
    best_acc = 0.

    starting_epoch_n = 0
    if training_was_in_progress:
        starting_epoch_n = int(optimizer_ckpt_path.split('_')[-1])
    for epoch in range(starting_epoch_n + 1, n_epochs + 1):
        model.train(True)
        dataloader = dataset.train_dataloader(epoch)

        for iter_n, batch in enumerate(dataloader):
            images = batch[0].to(device)
            targets = batch[1].to(device)

            model.zero_grad()
            outputs = model(images)
            if loss_type == 'binary':
                outputs = torch.softmax(outputs, dim = -1)
            loss = loss_function(outputs, targets)
            if loss_type == 'binary':
                acc = outputs.max(1)[1].eq(targets.max(1)[1])
            else:
                acc = outputs.max(1)[1].eq(targets)
            acc = acc.float().mean().detach().cpu()
            print(f'{epoch}, {iter_n}, {acc}', end = '\r')

            loss.backward()
            optimizer.step()

        model.eval()
        dataloader = ( dataset.val_dataloader() if has_val and 'student' not in model.name else dataset.test_dataloader())
        accs = 0
        n_samples = 0
        for iter_n, batch in enumerate(dataloader):
            images = batch[0].to(device)
            targets = batch[1].to(device)
            n_samples += targets.shape[0]

            with torch.no_grad():
                outputs = model(images)
                acc = outputs.max(1)[1].eq(targets).float().sum()
                acc = acc.detach().cpu()
            accs += acc
        accs /= n_samples
        print(f'{epoch}, {accs}                        ')
        if not has_val or 'student' in model.name:
            torch.save(model.state_dict(), ckpt_path)
        elif accs > best_acc:
            best_acc = accs
            torch.save(model.state_dict(), ckpt_path)
        new_checkpoint_path = f'{root_optimizer_ckpt_path}_{epoch}'
        torch.save(optimizer.state_dict(), f'./checkpoints/{new_checkpoint_path}')
        if os.path.exists(f'./checkpoints/{optimizer_ckpt_path}'):
            os.unlink(f'./checkpoints/{optimizer_ckpt_path}')
        optimizer_ckpt_path = new_checkpoint_path
    # os.unlink(f'./checkpoints/{optimizer_ckpt_path}')

class Generator(nn.Module):
    def __init__(self, ngpu = 1):
        super(Generator, self).__init__()

        self.block_1 = nn.Sequential(
            EqualLinear(256, 4 * 4 * 256),
            Reshape(-1, 256, 4, 4),
            PixelNormalization(),
            nn.LeakyReLU(negative_slope = 0.2),

            EqualConv2d(
                in_channels = 256,
                out_channels = 256,
                kernel_size = 3,
                stride = 1,
                padding = 1
            ),
            PixelNormalization(),
            nn.LeakyReLU(negative_slope = 0.2),
        )
        self.block_1_to_rgb = nn.Sequential(
            EqualConv2d(
                in_channels = 256,
                out_channels = 3,
                kernel_size = 1,
                stride = 1,
                padding = 0
            )
        )
        self.block_2 = nn.Sequential(
            nn.Upsample(
                scale_factor = 2,
                mode = 'bilinear'
            ),
            EqualConv2d(
                in_channels = 256,
                out_channels = 128,
                kernel_size = 3,
                stride = 1,
                padding = 1
            ),
            PixelNormalization(),
            nn.LeakyReLU(negative_slope = 0.2),
            EqualConv2d(
                in_channels = 128,
                out_channels = 128,
                kernel_size = 3,
                stride = 1,
                padding = 1
            ),
            PixelNormalization(),
            nn.LeakyReLU(negative_slope = 0.2),
        )
        self.block_2_to_rgb = nn.Sequential(
            EqualConv2d(
                in_channels = 128,
                out_channels = 3,
                kernel_size = 1,
                stride = 1,
                padding = 0
            )
        )
        self.block_3 = nn.Sequential(
            nn.Upsample(
                scale_factor = 2,
                mode = 'bilinear'
            ),
            EqualConv2d(
                in_channels = 128,
                out_channels = 64,
                kernel_size = 3,
                stride = 1,
                padding = 1
            ),
            PixelNormalization(),
            nn.LeakyReLU(negative_slope = 0.2),
            EqualConv2d(
                in_channels = 64,
                out_channels = 64,
                kernel_size = 3,
                stride = 1,
                padding = 1
            ),
            PixelNormalization(),
            nn.LeakyReLU(negative_slope = 0.2),
        )
        self.block_3_to_rgb = nn.Sequential(
            EqualConv2d(
                in_channels = 64,
                out_channels = 3,
                kernel_size = 1,
                stride = 1,
                padding = 0
            )
        )
        self.block_4 = nn.Sequential(
            nn.Upsample(
                scale_factor = 2,
                mode = 'bilinear'
            ),
            EqualConv2d(
                in_channels = 64,
                out_channels = 32,
                kernel_size = 3,
                stride = 1,
                padding = 1
            ),
            PixelNormalization(),
            nn.LeakyReLU(negative_slope = 0.2),
            EqualConv2d(
                in_channels = 32,
                out_channels = 32,
                kernel_size = 3,
                stride = 1,
                padding = 1
            ),
            PixelNormalization(),
            nn.LeakyReLU(negative_slope = 0.2),
        )
        self.block_4_to_rgb = nn.Sequential(
            EqualConv2d(
                in_channels = 32,
                out_channels = 3,
                kernel_size = 1,
                stride = 1,
                padding = 0
            )
        )
        self.block_5 = nn.Sequential(
            nn.Upsample(
                scale_factor = 2,
                mode = 'bilinear'
            ),
            EqualConv2d(
                in_channels = 32,
                out_channels = 16,
                kernel_size = 3,
                stride = 1,
                padding = 1
            ),
            PixelNormalization(),
            nn.LeakyReLU(negative_slope = 0.2),
            EqualConv2d(
                in_channels = 16,
                out_channels = 16,
                kernel_size = 3,
                stride = 1,
                padding = 1
            ),
            PixelNormalization(),
            nn.LeakyReLU(negative_slope = 0.2),
        )
        self.block_5_to_rgb = nn.Sequential(
            EqualConv2d(
                in_channels = 16,
                out_channels = 3,
                kernel_size = 1,
                stride = 1,
                padding = 0
            )
        )
        self.ngpu = ngpu
        self.upsample = nn.Upsample(
            scale_factor = 2,
            mode = 'bilinear'
        )

    def generate_1(self, input):
        return self.block_1_to_rgb(self.block_1(input))

    def generate_2(self, samples, alpha):
        old_output = self.block_1(samples)

        output = self.block_2_to_rgb(self.block_2(old_output))
        old_output = self.block_1_to_rgb(old_output)
        old_output = self.upsample(old_output)

        return old_output * (1. - alpha) + output * alpha

    def generate_3(self, samples):
        return self.block_2_to_rgb(self.block_2(self.block_1(samples)))

    def generate_4(self, samples, alpha):
        old_output = self.block_2(self.block_1(samples))

        output = self.block_3_to_rgb(self.block_3(old_output))
        old_output = self.block_2_to_rgb(old_output)
        old_output = self.upsample(old_output)

        return old_output * (1. - alpha) + output * alpha

    def generate_5(self, samples):
        old_output = self.block_2(self.block_1(samples))
        output = self.block_3_to_rgb(self.block_3(old_output))

        return output

    def generate_6(self, samples, alpha):
        old_output = self.block_3(self.block_2(self.block_1(samples)))

        output = self.block_4_to_rgb(self.block_4(old_output))
        old_output = self.block_3_to_rgb(old_output)
        old_output = self.upsample(old_output)

        return old_output * (1. - alpha) + output * alpha

    def generate_7(self, samples):
        old_output = self.block_3(self.block_2(self.block_1(samples)))
        output = self.block_4_to_rgb(self.block_4(old_output))

        return output

    def generate_8(self, samples, alpha):
        old_output = self.block_4(self.block_3(self.block_2(self.block_1(samples))))

        output = self.block_5_to_rgb(self.block_5(old_output))
        old_output = self.block_4_to_rgb(old_output)
        old_output = self.upsample(old_output)

        return old_output * (1. - alpha) + output * alpha

    def generate_9(self, samples):
        old_output = self.block_4(self.block_3(self.block_2(self.block_1(samples))))
        output = self.block_5_to_rgb(self.block_5(old_output))

        return output

    def forward(self, input):
        return self.generate_7(input)

class Reshape(nn.Module):
    def __init__(self, *args):
        super(Reshape, self).__init__()
        self.shape = args

    def forward(self, x):
        return x.view(self.shape)

class PixelNormalization(nn.Module):
    def __init__(self):
        super(PixelNormalization, self).__init__()

    def forward(self, output):
        return output / torch.sqrt(
            torch.unsqueeze(
                torch.mean(
                    torch.pow(output, 2),
                    dim = [1],
                ) + 1e-8,
                1
            )
        )

class EqualLR:
    def __init__(self, name):
        self.name = name

    def compute_weight(self, module):
        weight = getattr(module, self.name + '_orig')
        fan_in = weight.data.size(1) * weight.data[0][0].numel()

        return weight * sqrt(2 / fan_in)

    @staticmethod
    def apply(module, name):
        fn = EqualLR(name)

        weight = getattr(module, name)
        del module._parameters[name]
        module.register_parameter(name + '_orig', nn.Parameter(weight.data))
        module.register_forward_pre_hook(fn)

        return fn

    def __call__(self, module, input):
        weight = self.compute_weight(module)
        setattr(module, self.name, weight)


def equal_lr(module, name='weight'):
    EqualLR.apply(module, name)

    return module


class PixelNorm(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, input):
        return input / torch.sqrt(torch.mean(input ** 2, dim=1, keepdim=True)
                                  + 1e-8)


class EqualConv2d(nn.Module):
    def __init__(self, *args, **kwargs):
        super().__init__()

        conv = nn.Conv2d(*args, **kwargs)
        conv.weight.data.normal_()
        conv.bias.data.zero_()
        self.conv = equal_lr(conv)

    def forward(self, input):
        return self.conv(input)


class EqualConvTranspose2d(nn.Module):
    ### additional module for OOGAN usage
    def __init__(self, *args, **kwargs):
        super().__init__()

        conv = nn.ConvTranspose2d(*args, **kwargs)
        conv.weight.data.normal_()
        conv.bias.data.zero_()
        self.conv = equal_lr(conv)

    def forward(self, input):
        return self.conv(input)

class EqualLinear(nn.Module):
    def __init__(self, in_features, out_features):
        super().__init__()

        linear = nn.Linear(in_features, out_features)
        linear.weight.data.normal_()
        linear.bias.data.zero_()

        self.linear = equal_lr(linear)

    def forward(self, input):
        return self.linear(input)

def train_or_restore_cifar_100_6_classes_gan(generator):
    generator.load_state_dict(torch.load(
        './checkpoints/cifar_100_6_classes_gan',
        map_location = device
    ))
    generator.to(device)
    generator.eval()

    return generator

def evaluate(model, dataset):
    model.eval()
    dataloader = dataset.test_dataloader()
    accs = 0
    n_samples = 0
    for iter_n, batch in enumerate(dataloader):
        images = batch[0].to(device)
        targets = batch[1].to(device)
        n_samples += targets.shape[0]

        with torch.no_grad():
            outputs = model(images)
            acc = outputs.max(1)[1].eq(targets).float().sum()
            acc = acc.detach().cpu()
        accs += acc
    print(f'{model.name} accuracy: {accs / n_samples}')

class OptimizedFromGenerator(object):
    def __init__(
        self,
        generator,
        teacher,
        student,
        test_dataloader,
        soft_labels = True,
        device = torch.device('cuda'),
        to_grayscale = True,
        batch_size = 64,
        n_classes = 10,
        input_size = 32
    ):
        self.generator = generator
        self.teacher = teacher
        self.device = device
        self.test_dataloader = test_dataloader
        self.use_soft_labels = soft_labels
        self.to_grayscale = to_grayscale
        self.batch_size = batch_size
        self.n_classes = n_classes

    def train_dataloader(self, *args, **kwargs):
        optimization = optimize_to_grayscale if self.to_grayscale else optimize
        for _ in range(1000):
            if 'combined' in str(type(self.generator)).lower():
                # with Pool(4) as p:
                #     first_images = torch.cat(
                #         p.starmap(
                #             optimize_to_grayscale,
                #             [(self.teacher, self.generator.gan, 8, 128)] * 4
                #         ),
                #         axis = 0
                #     )
                # with Pool(4) as p:
                #     second_images = torch.cat(
                #         p.starmap(
                #             optimize_to_grayscale,
                #             [(self.teacher, self.generator.vae, 8, 100)] * 4
                #         ),
                #         axis = 0
                #     )
                # images = torch.cat(
                #     [first_images, second_images],
                #     axis = 0
                # )
                images = torch.cat((
                    optimize_to_grayscale(
                        self.teacher, self.generator.gan, batch_size = 32,
                        encoding_size = 128
                    ),
                    optimize_to_grayscale(
                        self.teacher, self.generator.vae, batch_size = 32,
                        encoding_size = 100
                    ),
                ), axis = 0)
            else:
                images = optimization(self.teacher, self.generator)

            with torch.no_grad():
                labels = self.teacher(images)
                if not self.use_soft_labels:
                    labels = labels.max(1)[1]
                else:
                    labels = torch.softmax(labels, dim = -1)
            yield (images, labels)

"""# Prepare"""

def prepare_generator():
    '''if generator == 'combined':
        vae = generator_dict['dcgan']()
        vae = generator_prepare_dict['dcgan'](vae)

        gan = generator_dict['gan']()
        gan = generator_prepare_dict['gan'](gan)

        class CombinedGenerator():
            def __init__(self, vae, gan):
                self.vae = vae
                self.gan = gan

                self.current_generator = self.gan
                self.current_state = 'gan'

            def __call__(self, inputs):
                return self.current_generator(inputs)

            def switch(self):
                self.current_generator = (
                    self.gan if self.current_state == 'vae' else self.vae
                )
                self.current_state = (
                    'gan' if self.current_state == 'vae' else 'vae'
                )

            def encoding_size(self):
                return 128 if 'gan' in self.current_state else 100

        return CombinedGenerator(vae, gan)'''

    #generator = generator_dict[env.generator]()
    generator = Generator
    #generator = generator_prepare_dict[env.generator](generator)
    generator = train_or_restore_cifar_100_6_classes_gan(generator)

    return generator

def prepare_teacher_student():

    #true_dataset = dataset_dict[env.true_dataset](input_size = env.size)
    true_dataset = CIFAR10(input_size = size)

    #teacher = predictor_dict[env.teacher]( name = teacher_name(env), n_outputs = true_dataset.n_classes)
    #teacher.to(device)
    teacher = initialize_model(teacher_name, true_dataset_n_classes)

    if optim == 'sgd':
        train_or_restore_predictor(teacher, true_dataset)
    else:
        train_or_restore_predictor_adam(teacher, true_dataset)
    teacher.eval()

    #student = predictor_dict[env.student]( name = student_name(env),  n_outputs = true_dataset.n_classes)
    #student.to(device)
    student = initialize_model(student_name, true_dataset_n_classes)

    return teacher, true_dataset, student

def prepare_student_dataset(env, teacher, teacher_dataset, student, generator):
    #dataset = dataset_dict[env.samples]( generator, teacher, student,
    #                                    test_dataloader = teacher_dataset.test_dataloader, to_grayscale = ('gan' in env.generator and 'fmnist' in env.true_dataset))
    dataset = OptimizedFromGenerator()(generator=generator, teacher=teacher, student=student, test_dataloader = teacher_dataset.test_dataloader,
        to_grayscale = ('gan' and 'fmnist'))

    return dataset

"""# main"""

if __name__ == '__main__':

    student_name = 'HalfAlexnet'
    teacher_name= 'Alexnet'

    teacher, teacher_dataset, student = prepare_teacher_student()
    evaluate(teacher, teacher_dataset)

    generator = prepare_generator()

    student_dataset = prepare_student_dataset(teacher, teacher_dataset, student, generator)

    if optim == 'sgd':
        train_or_restore_predictor(student, student_dataset, loss_type = 'binary', n_epochs = int(epochs))
    else:
        train_or_restore_predictor_adam( student, student_dataset, loss_type = 'binary', n_epochs = epochs)

    evaluate(student, teacher_dataset)